language: julia
julia:
  - release
  - nightly
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("MDPs", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("MDPs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
